### ISSUE TITLE
Object detection base model not detecting any objects

### ISSUE THREAD

**Issue by willcray** [googlesamples/mlkit#423] opened 2022-01-12 16:42 UTC
**Describe the bug**
The `process()` function for the object detection model returns an empty array of objects no matter what object(s) are in the view of the camera. I can change a few lines of code to switch my app from doing object detection to image labeling. Image labeling works for me: the log to check if the array is empty is false, and I can successfully access the label, confidence, etc. 

**Code Snippet**
```
public class VisionCameraObjectDetectionPlugin extends FrameProcessorPlugin {
  
  private final ObjectDetector objectDetector = ObjectDetection.getClient(ObjectDetectorOptions.DEFAULT_OPTIONS);

  @Override
  public Object callback(ImageProxy frame, @NotNull Object[] params) {
    @SuppressLint("UnsafeOptInUsageError")
    Image mediaImage = frame.getImage();
    if (mediaImage != null) {
      InputImage image = InputImage.fromMediaImage(mediaImage, frame.getImageInfo().getRotationDegrees());
      Task<List<DetectedObject>> task = objectDetector.process(image);

      try {
        List<DetectedObject> objects = Tasks.await(task);
        Log.d("XXX", String.valueOf(objects.isEmpty()));

      } catch (Exception e) {
        Log.d("XXX", "ERROR");
        e.printStackTrace();
      }
    }
    return null;
  }

  VisionCameraObjectDetectionPlugin() {
    super("detectObject");
  }
```

**Expected behavior**
I expect the list of objects to not be empty when I aim the camera at various objects.

**SDK Info:**
 - SDK Name & Version com.google.mlkit:object-detection:16.2.8

**Smartphone:**
 - Device/Simulator: Motorola Moto E (physical device)
 - Device/Simulator Android API 31

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: Android Studio 4.2.1 and Xcode 13.2
- Laptop/Desktop: Apple MacBook Pro 2020 16"
- Laptop/Desktop OS/version: macOS Monterrey 12.1

**Comment by steven-chengji-yan** [comment] 2022-01-12 20:26
To help investigate this issue, could you let us know if the ODT feature on the mlkit quickstart app work or not on your device? https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart

**Comment by willcray** [comment] 2022-01-13 17:29
> To help investigate this issue, could you let us know if the ODT feature on the mlkit quickstart app work or not on your device? https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart
> 
> If you are using CameraX, please try with the CameraXLivePreview. Letting us know if StillImageActivity and LivePreviewActivity work will be helpful as well.

All three of the activities you listed work properly on the device cited in the issue.

**Comment by willcray** [comment] 2022-01-13 18:34
I'm now receiving this Exception: 

`com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks`

After updating my code to the following: 

```
public class VisionCameraObjectDetectionPlugin extends FrameProcessorPlugin {

  private final ObjectDetector objectDetector = ObjectDetection.getClient(ObjectDetectorOptions.DEFAULT_OPTIONS);

  @Override
  public Object callback(ImageProxy frame, @NotNull Object[] params) {
    @SuppressLint("UnsafeOptInUsageError")

    Image mediaImage = frame.getImage();

    if (mediaImage != null) {
      InputImage image = InputImage.fromMediaImage(mediaImage, frame.getImageInfo().getRotationDegrees());
      Log.d("XXX", String.valueOf(image == null));

      Task<List<DetectedObject>> task = objectDetector.process(image);

      task.addOnSuccessListener(
          new OnSuccessListener<List<DetectedObject>>() {
            @Override
            public void onSuccess(List<DetectedObject> detectedObjects) {
              // Task completed successfully
              // ...
              Log.d("XXX", String.valueOf(detectedObjects.size()));
            }
          }
        )
        .addOnFailureListener(
          new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
              // Task failed with an exception
              // ...
              Log.d("XXX", e.toString());
            }
          }
        )
        .addOnCompleteListener(
          new OnCompleteListener<List<DetectedObject>>() {
            @Override
            public void onComplete(@NonNull Task<List<DetectedObject>> task) {
              frame.close();
              mediaImage.close();
            }
          }
        );
    }
    return null;
  }

  VisionCameraObjectDetectionPlugin() {
    super("detectObject");
  }
}
```

Similar issues are cited [here](https://stackoverflow.com/questions/56214555/android-mlkit-internal-error-has-occurred-when-executing-firebase-ml-tasks), and were resolved by adding the `onCompleteListener()` with `.close()` being called on  the `ImageProxy` and `Image` objects. However, I'm still receiving the error after adding it.

**Comment by steven-chengji-yan** [comment] 2022-01-13 18:55
I don't see anything obviously wrong with the code you provided. It could be related to the way you are using this class with other part of your code.

1. Does ImageLabeling work with the new code?
2. Could you see any other adb error logs other than the one you logged?
3. Where is the "UnsafeOptInUsageError" from? Could it be related?
4. Here is a tutorial about ODT+CameraX: https://medium.com/swlh/machine-learning-with-camerax-and-mlkit-fbed9dcd542b
5. If I were you, what I would try is to set up a basic working version of ODT+CameraX, and then start adding your code structure gradually to see which part cause it stop working.

**Comment by steven-chengji-yan** [comment] 2022-01-13 18:58
One small difference is that in our sample code, we will call ImageProxy#close.

**Comment by willcray** [comment] 2022-01-13 20:35
> I don't see anything obviously wrong with the code you provided. It could be related to the way you are using this class with other part of your code.
> 
> 1. Does ImageLabeling work with the new code?
> 2. Could you see any other adb error logs other than the one you logged?
> 3. Where is the "UnsafeOptInUsageError" from? Could it be related?
> 4. Here is a tutorial about ODT+CameraX: https://medium.com/swlh/machine-learning-with-camerax-and-mlkit-fbed9dcd542b
> 5. If I were you, what I would try is to set up a basic working version of ODT+CameraX, and then start adding your code structure gradually to see which part cause it stop working.

Yes, this code works and has multiple labels returned each frame:

```
public class VisionCameraObjectDetectionPlugin extends FrameProcessorPlugin {

//  private final ObjectDetector objectDetector = ObjectDetection.getClient(ObjectDetectorOptions.DEFAULT_OPTIONS);
    private final ImageLabeler labeler = ImageLabeling.getClient(ImageLabelerOptions.DEFAULT_OPTIONS);

  @Override
  public Object callback(ImageProxy frame, @NotNull Object[] params) {
    @SuppressLint("UnsafeOptInUsageError")

    Image mediaImage = frame.getImage();

    if (mediaImage != null) {
      InputImage image = InputImage.fromMediaImage(mediaImage, frame.getImageInfo().getRotationDegrees());
      Log.d("XXX", String.valueOf(image == null));

      Task<List<ImageLabel>> task = labeler.process(image);

      task.addOnSuccessListener(
          new OnSuccessListener<List<ImageLabel>>() {
            @Override
            public void onSuccess(List<ImageLabel> labels) {
              // Task completed successfully
              // ...
              Log.d("XXX", String.valueOf(labels.size()));
            }
          }
        )
        .addOnFailureListener(
          new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
              // Task failed with an exception
              // ...
              Log.d("XXX", e.toString());
            }
          }
        )
        .addOnCompleteListener(
          new OnCompleteListener<List<ImageLabel>>() {
            @Override
            public void onComplete(@NonNull Task<List<ImageLabel>> task) {
              frame.close();
              mediaImage.close();
            }
          }
        );
    }
    return null;
  }

  VisionCameraObjectDetectionPlugin() {
    super("detectObject");
  }
}
```

 I do however, get the same exception I receive on every frame on the object detection code about every ten frames using the code above.

**Comment by steven-chengji-yan** [comment] 2022-01-14 05:05
"I'm not sure how that would affect things when it clearly works with a different MLKit model."
Each ML Kit feature not only contains models but different pipeline code. For example, for face and object detection, there are tracking mode, while image labeling doesn't have tracking. 

At this moment, I still don't have too much clue about what is wrong given that the ML Kit sample app is working correctly. Do please share your findings here after you figure it out. It might be helpful for other developers as well. 

Thanks!

**Comment by steven-chengji-yan** [comment] 2022-01-14 05:10
Maybe you could try set the detector mode of ObjectDetectorOptions to be SINGLE_IMAGE (which disable tracking) and see if you can still reproduce the issue.

**Comment by willcray** [comment] 2022-01-14 16:33
> Maybe you could also try setting the detector mode of ObjectDetectorOptions to be SINGLE_IMAGE (which disable tracking) and see if you can still reproduce the issue.

Thank you for your help!

I tried running it in SINGLE_IMAGE mode with no luck. I was able to get more info from the debugger though. The cause of the MLKit exception is `java.lang.IllegalStateException: Image is already closed`. I receive this the first time my function is called.

**Comment by steven-chengji-yan** [comment] 2022-01-14 19:31
In this case, could you check if anyone else along the way calls close() on the imageProxy or the media.Image as well? If yes, you will need some coordination for those close(). The image should be really closed after all the consumers finish using it.

**Comment by willcray** [comment] 2022-01-17 20:15
I changed the code back to my original approach that initiated this thread:

```
  @Override
  public Object callback(ImageProxy frame, @NotNull Object[] params) {
    @SuppressLint("UnsafeOptInUsageError")

    Image mediaImage = frame.getImage();

    if (mediaImage != null) {
      InputImage image = InputImage.fromMediaImage(mediaImage, frame.getImageInfo().getRotationDegrees());
      Task<List<DetectedObject>> task = objectDetector.process(image);

      try {
        List<DetectedObject> detectedObjects = Tasks.await(task);
        Log.d("XXX", String.valueOf(detectedObjects.size()));
      } catch (Exception e) {
        e.printStackTrace();
        Log.d("XXX", e.toString());
      }
    }
    return null;
  }

  VisionCameraObjectDetectionPlugin() {
    super("detectObject");
  }
}
```

I no longer receive any errors. But again, I the object list returned by `.process()` is empty, despite trying the camera on many different objects. I can modify this code and ONLY change the ODT model to the image labeler model, and it successfully returns accurate image labels on each frame.

Is this not an issue with the ODT library/model itself?

**Comment by steven-chengji-yan** [comment] 2022-01-18 19:32
> Is this not an issue with the ODT library/model itself?

It is hard to say at the moment. What we know is that image labeling and ODT do not have the exact same implementation, so it is possible that image labeling can accept certain invalid input but ODT cannot.

Since you mentioned that the ML Kit sample app works fine, have you tried to go through the difference between your code and the sample and found anything? 

Also, have you tried to just use ODT and CameraX to write a barebone app without extra interface or code structure and see if that works? (I highly suggest to give this a try if you haven't done so). [Here is one tutorial](https://medium.com/swlh/machine-learning-with-camerax-and-mlkit-fbed9dcd542b) but I think you could find more on internet.

Did you check if the sample app and your code are using the same version of the ODT SDK?

**Comment by steven-chengji-yan** [comment] 2022-01-29 23:06
I am closing this due to no-reply. 

Feel free to re-open if you are still working on it.

**Closed by steven-chengji-yan** 2022-01-29 23:06 UTC
