### ISSUE TITLE
When a touch event occurs, Selfie Segmentation FPS is improved (from 10 to 30)

### ISSUE THREAD

**Issue by LeeChangki** [googlesamples/mlkit#312] opened 2021-06-10 00:47 UTC
I tested the 'selfie segmentation' example, and found that the fps increased when touching the screen.

Without a touch event: 10 fps
With a touch event(actually, pressing): 30 fps
(CPU and Memory usages do not change)
Test phone: Samsung Galaxy S9+

Does anyone know why this occurs?

**Comment by steven-chengji-yan** [comment] 2021-06-14 21:51
Hi LeeChangki,

I don't think the detector latency should be affected by the touch event.

Are you using the ML Kit vision quickstart example as is, without any change? What activity are you using? What image resolution are you using?

Also, could you verify the following things:
(1) Measure the detector latency. If you are using the ML Kit quickstart, you can type **adb logcat | grep "avg="** in terminal to check the detector latency in both cases to see if it changes.
(2) Try get the FPS of the camera input. It could be that the camera input is fed in faster when you touch the screen, while the detector latency per frame is the same.
(3) Try front and back cam, to see if the issue happens in both case. This is to understand whether it is more related to camera.
(4) Try CameraXLivePreviewActitivity and LivePreviewActivity, to see if the issue happens in both cases.
(5) In the Settings' page (tap on the gear button at the top-right corner of the UI), try enabling and disabling Live viewport and see if it makes any difference.

**Comment by LeeChangki** [comment] 2021-06-15 02:33
Hi, steven-chengji-yan

Thank you for replying!

I'm using **the ML Kit vision-quickstart android project segmenter example** without any change.
I tested Java and Kotlin version, and ran LivePreviewActivity and CameraXLivePreviewActivity each.
The image resolution was 352x288 for LivePreviewActivity and 640x480 for CameraXLivePreviewActivity.

(1) Log
(Java) LivePreviewActivity with front camera(352x288)
`
2021-06-15 10:43:11.071 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=13, avg=54
2021-06-15 10:43:11.071 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=12, avg=54
2021-06-15 10:43:12.015 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=13, avg=53
2021-06-15 10:43:12.015 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=12, avg=53
2021-06-15 10:43:13.027 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=13, avg=53
2021-06-15 10:43:13.027 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=12, avg=53
2021-06-15 10:43:14.028 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=13, avg=52
2021-06-15 10:43:14.028 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=12, avg=51
2021-06-15 10:43:15.020 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=13, avg=49
2021-06-15 10:43:15.020 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=12, avg=49
2021-06-15 10:43:16.034 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=13, avg=50
2021-06-15 10:43:16.034 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=12, avg=49
2021-06-15 10:43:17.083 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=13, avg=51
2021-06-15 10:43:17.084 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=12, avg=50
/** Touch Event**/
2021-06-15 10:43:18.029 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=11, avg=49
2021-06-15 10:43:18.029 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=11, avg=48
2021-06-15 10:43:19.028 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=11, avg=44
2021-06-15 10:43:19.028 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=11, avg=44
2021-06-15 10:43:20.029 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=11, avg=41
2021-06-15 10:43:20.030 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=11, avg=41
2021-06-15 10:43:21.020 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=11, avg=39
2021-06-15 10:43:21.020 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=10, avg=38
2021-06-15 10:43:22.025 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=11, avg=36
2021-06-15 10:43:22.025 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=10, avg=36
2021-06-15 10:43:23.023 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=330, min=11, avg=34
2021-06-15 10:43:23.023 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=330, min=10, avg=34
`

(Java) CameraXLivePreviewActivity with front camera(640x480)
`
2021-06-15 10:46:13.260 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=154, min=44, avg=108
2021-06-15 10:46:13.260 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=153, min=43, avg=107
2021-06-15 10:46:14.269 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=154, min=44, avg=106
2021-06-15 10:46:14.270 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=153, min=43, avg=106
2021-06-15 10:46:15.182 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=154, min=44, avg=106
2021-06-15 10:46:15.182 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=153, min=43, avg=106
2021-06-15 10:46:16.368 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=154, min=44, avg=108
2021-06-15 10:46:16.368 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=153, min=43, avg=107
2021-06-15 10:46:17.236 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=154, min=44, avg=108
2021-06-15 10:46:17.236 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=153, min=43, avg=108
2021-06-15 10:46:18.271 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=154, min=44, avg=109
2021-06-15 10:46:18.271 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=153, min=43, avg=109
2021-06-15 10:46:19.347 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=155, min=44, avg=110
2021-06-15 10:46:19.347 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=155, min=43, avg=110
2021-06-15 10:46:20.266 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=155, min=44, avg=111
2021-06-15 10:46:20.266 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=155, min=43, avg=110
/** Touch Event**/
2021-06-15 10:46:21.181 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=155, min=17, avg=103
2021-06-15 10:46:21.181 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=155, min=17, avg=103
2021-06-15 10:46:22.187 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=155, min=16, avg=88
2021-06-15 10:46:22.187 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=155, min=16, avg=88
2021-06-15 10:46:23.183 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=155, min=16, avg=77
2021-06-15 10:46:23.183 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=155, min=16, avg=77
2021-06-15 10:46:24.187 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=155, min=16, avg=69
2021-06-15 10:46:24.187 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=155, min=16, avg=69
2021-06-15 10:46:25.188 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=155, min=16, avg=63
2021-06-15 10:46:25.188 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=155, min=16, avg=63
2021-06-15 10:46:26.189 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Frame latency: max=155, min=16, avg=58
2021-06-15 10:46:26.189 19709-19709/com.google.mlkit.vision.demo D/VisionProcessorBase: Detector latency: max=155, min=16, avg=58
`
**The min latency value is reduced with touch event.**

(2) It could be an answer. However, the camera FPS seems 30. (I added a log in CameraPreviewCallback > onPreviewFrame function and checked it.)
If my approach measuring the FPS is wrong, please give me a guide.

(3)(4) The issue happens in both cases.

(5) When disabling the live viewport option, the FPS has reduced but it has the same issue.
Disable the live viewport option: avg 7 fps without touch event, 20 fps with touch event
Enable the live viewport option: avg 10 fps without touch event, 30 fps with touch event

**Comment by steven-chengji-yan** [comment] 2021-06-15 04:58
Thanks for the extra info.

When you say a touch event, do you mean tap the camera preview once, then the FPS will increase after that, OR the FPS only increases when you hold your finger on the screen and will drop when you release your finger?

This is a very interesting behavior. However, I cannot reproduce it on my test devices. Do you have other devices? Does it only happen on this device or also others?

**Comment by LeeChangki** [comment] 2021-06-15 05:40
the FPS only increases when you hold your finger on the screen and will drop when you release your finger? **YES**
(**while** holding my finger on the screen, the FPS increases.)

I only tested on Samsung Galaxy S9+. Let me check other devices... Would you tell me which device you use?

**Comment by steven-chengji-yan** [comment] 2021-06-15 05:48
I was using several Google Pixel devices (different versions).  Let me know what you find on your other devices.

**Comment by LeeChangki** [comment] 2021-06-15 06:08
I tested several Samsung Galaxy devices(S9+, Note9, S10 5G), and the same issue occurs.

**Comment by steven-chengji-yan** [comment] 2021-06-15 23:00
I managed to get two other devices: a Redmi Note8 with Android PKQ1 and a Samsung Galaxy A51 with Android RP1A.

On the Xiaomi device, I cannot reproduce the issue either, but on the Samsung device, I can reproduce it.

I will see if I can get more devices with other brand to confirm if this is a Samsung specific issue. (If you have other brand devices, please share your findings here as well.)

We do find some optimization related to touch event: [example](https://www.researchgate.net/publication/305655807_Tbooster_Adaptive_Touch_Boosting_for_Mobile_Texting). Could be related. Will dig more.

**Comment by steven-chengji-yan** [comment] 2021-06-15 23:19
For 2 mentioned above, I just verified this is not ML Kit specific. 

By replacing the ML Kit detection logic with some heavy pure math calculation, the calculation becomes faster as well when I hold the screen on my Samsung Galaxy A51.

At this point, I think this is out of the scope of ML Kit. I would suggest you to see if you can find similar performance issues reported on the internet or try to reach out to some Samsung dev group.

Close this for now.
Best,

**Closed** 2021-06-15 23:19 UTC
