### ISSUE TITLE
Pose estimation is ignoring image orientation

### ISSUE THREAD

**Issue by GuyNir0522247488** [googlesamples/mlkit#124] opened 2020-08-28 22:03 UTC
Hello,

Thank you for providing a pose estimation solution.
It looks like the ".orientation" field is ignored when invoking: poseDetector.results, since all the results are the same, regardless of what values are set in the orientation field.
I am using camera stream and converts the CMSampleBuffer directly to VisionImage, so I dont want to waste cycles converting to Image and rotating myself to up position.

In my case, my orientation is portrait, front camera, the results I am getting at:
X values represent the actual vertical axis
Y values represent the horizontal axis, and also in reverse.
It didn't change, no matter what values were used to describe the orientation.

Thank you,
Guy

**Comment by calren** [comment] 2020-08-31 17:36
Hey @GuyNir0522247488 , which `orientation` field are you referring to? 

From my understanding `VisionImage` has been renamed to `InputImage` in the new ML Kit. [InputImage](https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage) does allow you to input the `rotationDegrees`. Let us know if that helps or if there's anything else we can help clarify.

**Comment by miworking3** [comment] 2020-09-01 04:10
Hi @GuyNir0522247488, thank you for trying out the new Pose Detector API!

If I understand correctly, `VisionImage` is referring to the vision quickstart app of iOS, and it is the [SWIFT quickstart app](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift) that was being discussed here.

About the coordination, this behavior is working as designed: ML Kit is designed to return output coordinate  the same as the input coordinate across all vision detectors.

In the case described here, the X values and Y values looked weird because the  raw `CMSampleBufferRef` taken from the Portrait+Front camera is actually a  rotated one, that has Width > Height. ML Kit was designed to take this case easily: you can use the raw `CMSampleBufferRef` directly to init a `VisionImage` because ML Kit takes the input image as an already rotated one by default.
``` 
let visionImage = VisionImage(buffer: sampleBuffer)
```

The `.orientation`  is set to help the detector to understand the input image better, thus help to get a better detection result. However it is not related to the coordinations of the output points. So no matter what `.orientation` is set, as long as the person's face is on the left in the input image, the output face landmarks will get small `X`s, not small `Y`s.

The demo app is trying to give an example in handling the output points for the most common use case tho: to show the landmarks correctly on the `previewLayer`,  where the landmarks' coordination are converted  to the coordinate system of the previewLayer using functions similar to [`normalizedPoint(fromVisionPoint:, width:, height:, )` ](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift#L563-L572)

and the image is also [rotated](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift#L525-L547) to align with the coordinate system of the previewLayer:


which makes them live in the same coordinate system:
![Pose](https://user-images.githubusercontent.com/52680648/91793623-90e57000-ebcd-11ea-967d-ea4e17485c37.PNG)


With the design above, going to close this issue as working as intended. Pls feel free to re-open it if you have other questions. Thanks!

**Closed by miworking3** 2020-09-01 04:10 UTC
