### ISSUE TITLE
Barcode scanning -> Not being able to scan high density PDF417 on latest mlkit version

### ISSUE THREAD

**Issue by rjmangubat23** [googlesamples/mlkit#374] opened 2021-10-19 07:45 UTC
I am not able to scan high density PDF417 or a PDF417 containing large Base64 string value. 

See sample below: 
![image](https://user-images.githubusercontent.com/11598375/137863234-a86767da-60a0-42bb-84ea-44c9d407b60d.png)

The issue happens on latest version `com.google.mlkit:barcode-scanning:17.0.0` with Text Recognition v2 `com.google.mlkit:text-recognition:16.0.0-beta1` but does not happen in versions like `16.0.2` or older versions with Text Recognition v1 `com.google.android.gms:play-services-mlkit-text-recognition:16.1.0`. 

I also tried using the older version alongside Text Recognition v2 however I am getting a classdef error as shown below: 
![image](https://user-images.githubusercontent.com/11598375/137864318-1db0bc00-3c15-4d1d-a7d2-23333c6d7022.png)

Is there a workaround this by any chance?  

Thank you in advance! 😄

**Comment by SilverDestiny** [comment] 2021-10-30 00:54
Hi,

I tried both `com.google.mlkit:barcode-scanning:17.0.0` and `com.google.mlkit:barcode-scanning:16.2.0` for your image and both cannot detect this barcode.
Could you provide a clear image that the barcode could be detected by any barcode version?

And as you mentioned you used text recognition together with barcode scanning, what is text recognition used in your case? Is it related to the barcode scanning function?

The app I used is the ML Kit quickstart app which is also using text recognition together: https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart

**Comment by rjmangubat23** [comment] 2021-11-05 17:17
Hello @SilverDestiny 

can you please try this one? 

![barcode](https://user-images.githubusercontent.com/11598375/140551692-2b5e8666-afd2-4ce7-9c07-6b2aeda4cf30.png)



I used text recognition on a separate case or function on our app mainly using for MRZ reading not directly related to this. However, I am getting the class def error as shown above when I use the latest version for both. It mostly happens when I scan the PDF417 or any barcode.

**Comment by SilverDestiny** [comment] 2021-11-10 02:57
The older version (`16.0.2`) is somehow not compatible with Text V2 together for some common SDKs upgrade.

https://user-images.githubusercontent.com/11598375/140551692-2b5e8666-afd2-4ce7-9c07-6b2aeda4cf30.png

I tried this image with `com.google.mlkit:barcode-scanning:17.0.0` and it seems detectable in static image mode but very hard in streaming mode. The image resolution needs to set up very high for this high density PDF417 barcode.

I also checked ``com.google.mlkit:barcode-scanning:16.0.2` and it looks the older didn't perform better than the latest version. You mean `com.google.mlkit:barcode-scanning:17.0.0` performed better and could easily detect this barcode?

**Comment by rjmangubat23** [comment] 2021-11-10 09:23
@SilverDestiny yes so the issue is in streaming mode and yes I did have to set to very high resolution and did some changes on the initial configuration of the camera.  

However, it only worked on the older version (`16.0.2`) and not the latest one (`17.0.0`). 

So ultimately, I am having problems upgrading to Text V2 because it will either break the barcode scanner part of our app if I use the older version `16.0.2` or scanning will not work entirely at all for the latest one (`17.0.0`).  

May I ask your help on this one? 

thank you very much in advance!

**Comment by SilverDestiny** [comment] 2021-12-10 03:06
Checked within the team and it is expected that the latest SDK may not work with other older SDKs because of the common dependency.
We'll work on fixing it on the latest release if this is a regression from the old barcode SDK.

**Comment by SilverDestiny** [comment] 2022-09-12 17:37
Close this issue as it's been over 6 months.
Please reopen it if anything is needed.

**Closed by SilverDestiny** 2022-09-12 17:37 UTC
