### ISSUE TITLE
Issue using Google MLKit Barcode scanning

### ISSUE THREAD

**Issue by Westflag** [googlesamples/mlkit#169] opened 2020-10-23 10:19 UTC
Hi!
I am using MLKit in my project. I found an issue with detecting barcodes (most of the scanned barcode was EAN 13).
In some cases, the library provides a wrong result(attached image). This issue reproduces on Android and IOS platforms.
![Screenshot_2020-10-23-12-48-00-938_com google mlkit md](https://user-images.githubusercontent.com/11146703/96992324-6612fa80-1532-11eb-933c-a9ae4e07dd08.png)

**Comment by miworking3** [comment] 2020-10-23 18:16
Hey could you share more information about the iOS device and OS version you used? It was able to detect the correct value with this app on the given image:

![ean](https://user-images.githubusercontent.com/52680648/97039310-16780300-1521-11eb-9aa7-0f8e88696b40.jpg)

**Comment by cs-googler** [comment] 2020-10-23 19:42
Could you share the os version and device make info for android as well?  I was able to detect the correct value with mlkit quick start app on the given image:
<img width="409" alt="Screen Shot 2020-10-23 at 12 39 34 PM" src="https://user-images.githubusercontent.com/62129746/97047025-2ac1fd00-152d-11eb-9f75-8b0b3f134085.png">

**Comment by Westflag** [comment] 2020-10-26 08:07
> Could you share the os version and device make info for android as well? I was able to detect the correct value with mlkit quick start app on the given image:
> <img alt="Screen Shot 2020-10-23 at 12 39 34 PM" width="409" src="https://user-images.githubusercontent.com/62129746/97047025-2ac1fd00-152d-11eb-9f75-8b0b3f134085.png">

I was using Xiaomi ReadMi 4A, Android 7.1.2 but it reproduces also on Pixel 3 XL and Samsung S7.
Please scan more and from different distances, it doesn’t reproduce always.

**Comment by belozierov** [comment] 2020-10-26 09:19
On iOS I also have such problem offen (for example, on iPhone X iOS 14.0.1).

**Comment by miworking3** [comment] 2020-10-26 14:26
For real-time barcodes scanning, the scanning result can be optimized by tuning the resolution as well as the distance for it. 
https://developers.google.com/ml-kit/vision/barcode-scanning/ios#performance-tips

Could you also share the capture session presets that is used in the detection? 
And is it always returning wrong result or is it just at some distance?

I don't have an iPhone X at hand, so I tried with iPhone 8, it doesn't reproduce on it with video mode either.  Will try to get a device to reproduce it.

**Comment by Westflag** [comment] 2020-10-26 14:56
On Android, I set resolution 1920x1080, distance is different 15-50 cm, and frequency of the wrong scan barcodes also. For example, it could be 1 per 5 or 1 per 10, or 1 per 20 attempts.

**Comment by Westflag** [comment] 2020-11-04 08:34
@miworking3 @cs-googler Hi! Do you have any updates on it?

**Comment by cs-googler** [comment] 2020-11-06 19:23
Yes, I can reproduce this with your setting by moving the camera. We will check if there is anything we can do to improve this.

**Comment by miworking3** [comment] 2020-11-20 15:41
Hi Westflag,

After double checking with our research team, I'm afraid this error is expected: EAN-13 has 12 digits data and 1 checksum digit. In the case that vision engine decodes both of these incorrectly because of the noise, but it happens to be satisfying checksum calculation. So, in the end it appears in the result. To mitigate the error, implementing majority voting at the client side may help here.

Thanks for reporting this and help us to identify and improve. We would update our document to include this as known-issue, thanks!

**Comment by Westflag** [comment] 2020-11-24 09:05
Hi miworking3,
Thank for the update ;)

**Comment by Westflag** [comment] 2020-11-24 15:20
Hi, @miworking3, @cs-googler 
I also found one more barcode that I can't scan 
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/11146703/100113723-4c3e3d80-2e79-11eb-9d09-92ce9e589ff9.png)

**Comment by miworking3** [comment] 2020-12-09 16:58
Hi @Westflag ,

Thanks for the data point.
We verified that this can be reproduced at our end as well, and it will be fixed on the next version, more insights from our research team on this: 
```Looking at the image and its binarized version, it has a print issue. You can see print ink is leaking on the edge and so white part is not very clear between two thin bars. This causes rule based barhopper-v2 to fail, but DL based barhopper-v3 handles this type  of cases well.```

and an update to the previous issue: we've already added this part to our website on the [handling for video frames](https://developers.google.com/ml-kit/vision/barcode-scanning/ios#performance-tips): 
```If you are trying to recognize barcodes from a sequence of streaming video frames, the recognizer might produce different results from frame to frame. You should wait until you get a consecutive series of the same value to be confident you are returning a good result.```



Please let us know if you have more concerns. 

Thanks!

**Closed by miworking3** 2020-12-09 16:58 UTC

**Comment by felipetce** [comment] 2021-10-30 02:37
I have the version 16.0.2 and the same problem happens
