### ISSUE TITLE
GoogleDataTransport dependency

### ISSUE THREAD

**Issue by PerLycke** [googlesamples/mlkit#300] opened 2021-05-19 16:27 UTC
Latest MLKitCommon version 2.1.0 on iOS depends on:

`GoogleDataTransport": "~> 8.0`

While newer Firebase libs depends on 9.0, creating the following issue:

`CocoaPods could not find compatible versions for pod "GoogleDataTransport"`

Please update the GoogleDataTransport dependency for iOS.

Cheers!

**Comment by brianmtully** [comment] 2021-05-24 18:26
Can we get an update on this issue?

**Comment by bcdj** [comment] 2021-05-25 20:57
This is a duplicate of another issue that we are still working on to fix: https://issuetracker.google.com/issues/187979605

**Closed by bcdj** 2021-05-25 20:57 UTC
