### ISSUE TITLE
couldn't find "libbarhopper_v3.so"

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [googlesamples/mlkit#663] opened 2023-05-04 10:03 UTC
Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.scan.lens-0jPNRELAyehNJBII1WkDQQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.scan.lens-0jPNRELAyehNJBII1WkDQQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libbarhopper_v3.so"

my sdk version:17.1.0

**Comment by zhouyiself** [comment] 2023-06-23 19:18
Duplicate of #681

**Closed by zhouyiself** 2023-06-23 19:18 UTC
