### ISSUE TITLE
[Bug report] Image Labeling giving wrong or inaccurate results.

### ISSUE THREAD

**Issue by mihirmodiofficial** [googlesamples/mlkit#601] opened 2022-12-16 05:09 UTC
Image Labeling giving wrong or inaccurate results. I have attached below test images

1st Image a Girl with goggles and hat -> Hat is not returning as result

2nd Image a boy with scarf or mask -> Scarf is not returning as result

3rd Image a man with cap -> Cap is not returning as a result

4th Image is of bollywoord actor hrithik roshan -> it is returning dog as result 

**SDK Info:**
 - SDK Name & Version com.google.android.gms:play-services-mlkit-image-labeling:16.0.8

**Smartphone:**
 - Device/Simulator: Redmi Note 7 Pro
 
 
![image](https://user-images.githubusercontent.com/35575044/208026863-c30a070f-4072-441b-bdaf-ad69ceed73bd.png)
 
![image](https://user-images.githubusercontent.com/35575044/208026805-ebf16213-edae-4e2a-bfdf-552f0c30045d.png)

![image](https://user-images.githubusercontent.com/35575044/208026781-e5a05c2c-793e-4ab0-9a30-6896f8c50546.png)

 - Device/Simulator OS: Android API 30

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: [e.g. Xcode 13.1, Android Studio 4.2]
- Laptop/Desktop: [e.g. iMac Pro (2017), HP Z840 Workstation]
- Laptop/Desktop OS/version: [e.g. macOS 12.0.1]

**Comment by SilverDestiny** [comment] 2023-01-03 23:58
Hi,

You could set the confidence score lower in `ImageLabelerOptions` to see if you can see your desired result in the result list.

Please note that Image labeling labels the WHOLE image for labels, so that the confidence might low if the object occupies very small portion of the image, e.g. the hat in the 1st image.

For model improvement, ML Kit will consider upgrading the model in future releases. Thanks for the report!

FYI it seems you forgot attaching the 2nd image to match your description.

**Comment by mihirmodiofficial** [comment] 2023-01-04 05:26
![image](https://user-images.githubusercontent.com/35575044/210489871-dcbae9a5-57aa-4e0e-9b6a-f7ef27035c64.png)

**Comment by mihirmodiofficial** [comment] 2023-01-04 05:27
> Hi,
> 
> You could set the confidence score lower in `ImageLabelerOptions` to see if you can see your desired result in the result list.
> 
> Please note that Image labeling labels the WHOLE image for labels, so that the confidence might low if the object occupies very small portion of the image, e.g. the hat in the 1st image.
> 
> For model improvement, ML Kit will consider upgrading the model in future releases. Thanks for the report!
> 
> FYI it seems you forgot attaching the 2nd image to match your description.

it doesn't matter if i set confidence score low. in 4th image it is returning dog as you can see there is no dog in the image

**Comment by SilverDestiny** [comment] 2023-01-04 07:50
Could you share the original image of the 4th image so that I can try to reproduce it on my end?

It shows "Concert" as the top result for me when I run image labeling, and there is no "dog" in the result list.

**Comment by mihirmodiofficial** [comment] 2023-01-04 10:21
![image](https://user-images.githubusercontent.com/35575044/210534298-e6cb343f-de6b-471b-8c96-2dac5439842f.png)

**Comment by SilverDestiny** [comment] 2023-01-04 17:19
![image](https://user-images.githubusercontent.com/29959194/210612555-3de090e8-24a4-4ae6-a9fa-33119ee65f95.png)

I tried this image using ML Kit vision quickstart app: https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart

Did you get the same result list?

**Comment by mihirmodiofficial** [comment] 2023-01-05 05:09
Yes you can see Dog in result with confidence score more than 50%

**Comment by SilverDestiny** [comment] 2023-01-10 23:30
Thanks for reporting this issue! We're looking into it internally and will improve in the near future releases.

**Comment by vasanthbalaji88** [comment] 2023-02-15 10:41
@SilverDestiny 

i'm using ml kit image labelling(custom model from firebase) in flutter, image labelling is perfect in IOS version, but in android it is giving poor results, results are inaccurate.
dependencies {
  // ...
  // Use this dependency to use the dynamically downloaded pipeline in Google Play Services
  implementation 'com.google.android.gms:play-services-mlkit-image-labeling-custom:16.0.0-beta4'
}

using above implementation for custom model in android

i used tflite plugin(Imagelabelling) in flutter , i have used same model in android to chek accuracy, it is working fine in tflite plugin  showing nearly 75-90% accuracy.

Could you please tell me , when this will be resolved in ml kit.

**Comment by SilverDestiny** [comment] 2023-03-06 17:38
> @SilverDestiny
> 
> i'm using ml kit image labelling(custom tflite model) in flutter, image labelling is perfect in IOS version, but in android it is giving poor results, results are inaccurate. dependencies { // ... // Use this dependency to use the dynamically downloaded pipeline in Google Play Services implementation 'com.google.android.gms:play-services-mlkit-image-labeling-custom:16.0.0-beta4' }
> 
> using above implementation for custom model in android
> 
> i used tflite plugin(Imagelabelling) in flutter , i have used same tflite custom model in android to chek accuracy, it is working fine in tflite plugin showing nearly 75-90% accuracy.
> 
> Could you please tell me , when this will be resolved in ml kit.

Could you elaborate how the results are poor in your case? And also could you try the bundled version `com.google.mlkit:image-labeling-custom:17.0.1` to see if it can give accurate results? Thanks!

**Comment by vasanthbalaji88** [comment] 2023-03-07 03:35
@SilverDestiny 
Thank you for your response, i tried with **com.google.mlkit:image-labeling-custom:17.0.1** bundled version as well , it is also not showing accurate results.

im using custom model for classification of Foods , i created this custom model(958 food items/labels ) using google colab with tensorflow.i have hoisted this custom model in firebase and download it from firebase. im using flutter plugin of mlkit [(https://pub.dev/packages/google_mlkit_image_labeling)], where im getting accurate results in IOS , but in android ,results are inaccurate, im capturing photo of any food item and then the plugin process the image and classifies the image.

**Comment by SilverDestiny** [comment] 2023-03-07 19:57
@vasanthbalaji88
Hmm, that's strange. iOS and Android should perform the same if they're using the same model. Not sure how the flutter plugin works https://pub.dev/packages/google_mlkit_image_labeling

Could you share the model by any chance? If not, maybe you could try to use ML Kit libraries directly without the plugin to see if it works as expected. Or could you share the same picture and results run by iOS and Android, then we can take a further look.

**Comment by vasanthbalaji88** [comment] 2023-03-08 03:37
@SilverDestiny 
Ya sure ,please find the model  as well as labels in below link
**https://we.tl/t-NlZrAHSSv1**
![Food IOS](https://user-images.githubusercontent.com/7520469/223612353-f785d5b1-5908-463c-a3cb-aa250c9afb18.png)
You can check in above image that BreadOmlette is showing in top of the list in IOS.

![Food Android](https://user-images.githubusercontent.com/7520469/223612478-e42bf1f8-c269-4df3-8115-7ee01dacc429.png)
In Android , it is not showing Breadomlette in the list itself.

You can check the food items from labels.txt file and search the food items from google search Photos, capture it and process the image. i have captured Bread Omlette from google search Photos

**Comment by SilverDestiny** [comment] 2023-03-13 17:44
@vasanthbalaji88 
I tried the bread omelette image(https://www.indianhealthyrecipes.com/wp-content/uploads/2019/04/bread-omelette.jpg) with ML Kit vision sample app on github: https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart

The result looks like:
![Screenshot_20230314-043830](https://user-images.githubusercontent.com/29959194/224784046-445618db-8ea0-4c43-b85d-88118e7877db.png)

It seems the result looks okay and Bread Omelette is the top label with 22+%.

Could you try our ML Kit vision sample app to see if the results look good?

**Comment by SilverDestiny** [comment] 2023-03-13 19:09
And FYI this the result from ML Kit iOS vision sample app (https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision):
![image](https://user-images.githubusercontent.com/29959194/224805028-a301d89c-6c11-4eea-bfbf-390d680c82d5.png)

As you can the scores are not consistent between iOS and Android, but the top labels are both Bread Omelette

**Comment by vasanthbalaji88** [comment] 2023-03-17 04:38
@SilverDestiny 

Thank you so much for confirming, that it is working in Android as well, I will ask the flutter plugin developer to check the details in Android section.

**Comment by SilverDestiny** [comment] 2023-04-28 21:56
Feel free to reopen it if you still have issue

**Closed by SilverDestiny** 2023-04-28 21:56 UTC
