### ISSUE TITLE
[Bug report] iOS app crashes: Expected MLKObject but found MLKDefaultObject

### ISSUE THREAD

**Issue by HafizAhsan1** [googlesamples/mlkit#415] opened 2021-12-24 14:17 UTC
**Describe the bug**
As soon as capture session starts, app gets crashed while running on debug/development mode and console produces the following exception
Swift/ArrayBuffer.swift:510: Precondition failed: NSArray element failed to match the Swift Array Element type
Expected MLKObject but found MLKDefaultObject
**To Reproduce**
Although the crash is very random and does not have any specific steps to be reproduced but following steps can be taken to reproduce the behavior in sample app:
1. As soon as camera opens ( captures session starts ), block the camera with hand and shake the phone until you get a crash.
2. Give the application a run 6-8 times while on debug mode (development profile) and app will crash randomly as soon as capture starts.
3. On crash, Xcode will show the reason as "Swift/ArrayBuffer.swift:510: Precondition failed: NSArray element failed to match the Swift Array Element type
Expected MLKObject but found MLKDefaultObject"

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
The application should not crash even on debug mode.

**SDK Info:**
 - SDK Name & Version ['GoogleMLKit/ObjectDetection' (Latest one installed by Pod Install) ]

**Smartphone:**
 - Device/Simulator: [e.g.iPhone 12 Pro Max]
 - Device/Simulator OS: [e.g. iOS 14.7.1]

**Development Environment:**
- IDE Eversion: [e.g. Xcode 13.1]
- Laptop/Desktop: [e.g. Macbook Pro M1 Pro]
- Laptop/Desktop OS/version: [e.g. macOS 12.0]

**Comment by bcdj** [comment] 2022-01-05 01:25
The error indicates Swift/ArrayBuffer.swift:510.  I'm curious what you have on and around line 510 of Swift/ArrayBuffer.swift... 
 Can you reproduce the issue using ML Kit's [quickstart sample app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision )?  It contains a [swift app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision/VisionExample) doing Object Detection and Tracking which returns [an array of `Object`](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift#L456).

**Comment by bcdj** [comment] 2022-01-05 03:43
Looks like you are cross posting [the same question on StackOverflow](https://stackoverflow.com/questions/70467142/getting-ios-app-crashed-on-detecting-frames-and-reason-is-expected-mlkobject-bu) as well.  Let's close this github bug report here and use the StackOverflow post for further discussion.

**Closed by bcdj** 2022-01-05 03:43 UTC
