### ISSUE TITLE
Are there any plans to support Swift Package Management?

### ISSUE THREAD

**Issue by TQBrowser** [googlesamples/mlkit#403] opened 2021-12-03 18:15 UTC

**Comment by bcdj** [comment] 2021-12-07 02:03
Due to necessary internal infra is still being developed, we cannot add the SPM support yet.  Closing this issue since it's a duplicate of the following one: https://github.com/googlesamples/mlkit/issues/180

**Closed by bcdj** 2021-12-07 02:03 UTC

**Comment by bcdj** [comment] 2021-12-14 06:37
@TQBrowser To help us gauge the importance of supporting Swift Package Manager, could you share the size of your user base? And if you can also provide an App Store link to your app, that would be helpful too.

**Comment by bcdj** [comment] 2021-12-14 06:41
Also, are you able to use Cocoapods in place of Swift Package Manager when building your app?  Will the lack of Swift Package Manager support block your development entirely?
