### ISSUE TITLE
[ML Kit] Does not detect qrcode, but google lens detects it easily

### ISSUE THREAD

**Issue by hiren1771** [googlesamples/mlkit#288] opened 2021-05-13 11:13 UTC
Could the team please look at this one and help me out. Thanks!
https://issuetracker.google.com/issues/187979605

**Comment by bcdj** [comment] 2021-06-08 17:55
Closing this report as a duplicate of https://issuetracker.google.com/issues/187979605.

**Closed by bcdj** 2021-06-08 17:55 UTC
