### ISSUE TITLE
Pose Estimation Has Flicker Problems on iOS

### ISSUE THREAD

**Issue by yubeiluo** [googlesamples/mlkit#206] opened 2020-12-16 03:13 UTC
Hi Team,

We are currently using Pose Estimation API on iOS to detect golf swings either from a live camera feed or an existing video file. It worked well in the beginning, but after more extensive testing, it is observed that the API would sometimes fail to detect poses intermittently resulting in what we call a flickering effect. We have also compared it with Apple's Vision framework and found out that Vision's Pose API has no such issues. Please find below two videos for a demo of this issue.

[flicker.zip](https://github.com/googlesamples/mlkit/files/5700054/flicker.zip)

Please be advised.

Thanks,

**Comment by yubeiluo** [comment] 2020-12-29 11:22
Hi Team and @miworking,

Any updates on this issue?

Thanks,

**Comment by miworking3** [comment] 2020-12-29 18:11
Thanks for reporting this issue @ yubeiluo, I tried to reproduce the flicker problem with this sample app on an iPhone 8+ in Release mode, but failed.

To further investigate this problem, could you help to provide more details:
(1) Which device were you running the app on?
(2) Was it running with the "Release" mode or "Debug" mode?
(3) Which Pose detector was it running on, "Pose" or "Pose Accurate"?
(4) Could you help to upload the original video without recognition marks on it? Tried to point the camera onto the video in the zip file, but the recognition was pretty bad as the green marks would confuse the detector. So I tried to run in with a similar golf video, which runs pretty well(see the attachment). Not sure if it is the noise from the marker or the other person in the screen that caused confusion to the pose detector, so it will be great if we can investigate with the original video without marks.

Thanks,

https://user-images.githubusercontent.com/52680648/103304657-0ddaf780-49be-11eb-9ac1-fe15f949d059.mov

**Comment by Misa-XU** [comment] 2021-01-08 15:16
I met a similar but more complicated situation... 

**Process:** I made the images from avcapturesession, fed it to face detector and pose detector serially (in the same queue, one by one), then rendered the results on the screen. 

**Outcome:**
1. Run with Xcode + Cable connected: In 80 percent of the cases it works well without flickering. 
2. Full battery:  In 90 percent of the cases, the face detector **flickering severely** -> **once I moved the app to background and brought it to foreground again, it works well (accurate and stable)...**

When running two networks together, the CPU Utils is about 70%, with a usage of memory about 150 MB.

**My Test Environment:**

> Device: iPad pro 2nd generation
> OS Version: 14.3
> Mode: Both Release and Debug
> Model: Pose and Pose Accurate
> 


Please find the video below. The size of frame is 1280 * 720 (I thought the face is large enough to undertake smile detection). The big circle in the upper middle shows the score of smiling (red for unhappy, green for happy, gray for no face detected).


[video.zip](https://github.com/googlesamples/mlkit/files/5787906/video.zip)

**Comment by yubeiluo** [comment] 2021-01-09 09:36
Hi @miworking3, thanks for your insights and sorry for my late reply. I thought I would receive email notifications for replies but didn't. I will keep a close watch on this issue now and please find below my answers to your questions:

(1) Which device were you running the app on? **- iPhone 11 Pro with iOS 14.2**

(2) Was it running with the "Release" mode or "Debug" mode? - **Debug Mode**

(3) Which Pose detector was it running on, "Pose" or "Pose Accurate"? **- Pose Accurate because accuracy matters more**

(4) Could you help to upload the original video without recognition marks on it? Tried to point the camera onto the video in the zip file, but the recognition was pretty bad as the green marks would confuse the detector, so tried it with a similar golf video, which runs pretty well(see the attachment). Not sure if it is the noise from the marker or the other person in the screen that caused confusion to the pose detector, so it will be great if we can investigate with the original video without marks. - **I attached the original video as requested. In fact, I found out that the flicker issue did occur quite often in the face on camera angle when I went to a golf course and filmed my golfer buddy in a live capture. Apart from Apple's Vision, I also tried OpenPose to perform the pose estimation and both had no such issues.**

https://user-images.githubusercontent.com/891170/104088211-17a70980-52a0-11eb-98d5-ab81f7142cb9.MOV

**Comment by miworking3** [comment] 2021-01-11 14:44
Thanks for the the original video, I can reproduce the flicker on my device, will touch research team to look more into this. Thanks!

**Comment by miworking3** [comment] 2021-01-12 20:01
It's a problem comes from the model, MLKit will release the next version of Pose Detection API in this month on 26th, and it works well with the new version. 
Please stay tuned and reopen this thread if it is not fixed on the next release. 
Thanks for reporting this bug!

**Closed by miworking3** 2021-01-12 20:01 UTC

**Comment by duckyngo** [comment] 2021-01-13 01:54
I also see this problem in android too. Even two frames are almost the same but the model failed to detect the pose in one. The MLKit and Mediapile are using the same model but The Mediapile works fine. Hope that we have a better model in the next version

**Comment by yubeiluo** [comment] 2021-01-13 06:15
@miworking3 this is great and your timely help is much appreciated. I'll test the new version once it is released as scheduled and keep u informed about the results.

**Comment by pratimash** [comment] 2022-02-11 05:54
Thanks for the reply. I downloaded master branch code from below link https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision.
Tried running Vision ios sample in iPhone 11, 14.3. Xcode 12.4.

In the attached video we can see, points, lines are moving even if person is standing stable.

https://user-images.githubusercontent.com/71701808/153543688-57415c2b-70d7-461d-b83b-16e338ac2f76.mp4

**Comment by pratimash** [comment] 2022-02-14 10:09
Hi Team and @miworking3 ,

Any updates on this issue?

Thanks,

**Comment by miworking3** [comment] 2022-02-15 15:47
Thanks, we will look into this.

**Comment by bcdj** [comment] 2022-02-20 01:10
@yubeiluo There are likely two causes to the flickering issue:  

1) Your app is built in the **Debug Mode**. It runs much slower. Try build in the **Release Mode**. The flickering should be reduced.

2) The "flicker_original_video.MOV" you provided was a video shot on a phone held by hand. You can see the video is not stable due to the natural shaking of the hand.

(1) is likely the primary reason for the significant flickering you are seeing.  With a release build, I could not reproduce the significant flickering. Please see the video I shot when testing on a device older than yours: iPhone 8 running iOS 11.4.1:

https://user-images.githubusercontent.com/16520568/154824486-4bbd05c8-3c2a-4015-abf7-b100108dd364.mov

There are still some flickering, but likely due to (2).

@pratimash In your video "Flicker.mp4", it was also shot on a phone held by hand and the hand was naturally shaking (you can see the movement of the legs of the chairs, even though the chairs were not moving themselves). The person in the video was mostly stable, but not entirely still (his body and arms were slightly moving).

**Comment by pratimash** [comment] 2022-02-21 12:05
> @yubeiluo There are likely two causes to the flickering issue:
> 
> 1. Your app is built in the **Debug Mode**. It runs much slower. Try build in the **Release Mode**. The flickering should be reduced.
> 2. The "flicker_original_video.MOV" you provided was a video shot on a phone held by hand. You can see the video is not stable due to the natural shaking of the hand.
> 
> (1) is likely the primary reason for the significant flickering you are seeing. With a release build, I could not reproduce the significant flickering. Please see the video I shot when testing on a device older than yours: iPhone 8 running iOS 11.4.1:
> 
>  flicker_iphone_8.mov 
> There are still some flickering, but likely due to (2).
> 
> @pratimash In your video "Flicker.mp4", it was also shot on a phone held by hand and the hand was naturally shaking (you can see the movement of the legs of the chairs, even though the chairs were not moving themselves). The person in the video was mostly stable, but not entirely still (his body and arms were slightly moving).
 
Thanks for the inputs. I will consider both the points and check again.

**Comment by eleiannu** [comment] 2022-03-02 01:14
@bcdj I'm experiencing flickering issues too when building in Release Mode the Swift Version. I do not get the same unwanted effect when running the ObjectiveC one. In particular, I get it with every detector I try. Do you know what the reason for that could be?

https://user-images.githubusercontent.com/48253305/156275813-231592e8-3b30-42a0-9fd4-23223ac6fa05.mp4

.

**Comment by bcdj** [comment] 2022-03-03 05:29
@eleiannu This issue is about Pose Detection, but the video you posted above is about Face Detection. Could you open a separate issue for that? You can also try out our [quickstart VisionExample sample app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision/VisionExample) which supports [Face Detection](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift#L179).  I don't observe the behavior you saw using the quickstart sample app.

**Comment by eleiannu** [comment] 2022-03-04 02:56
@bcdj the flickering I'm experiencing is showing up also in the Pose Detection and every detector I try. I was running the quickstart app
