### ISSUE TITLE
Bundled version tries to download model and fails. Affecting face-detection:16.1.0, 16.0.7 working fine

### ISSUE THREAD

**Issue by jjkavalam** [googlesamples/mlkit#310] opened 2021-05-30 12:50 UTC
I followed the steps below:

- Use 16.0.7

```
    implementation 'com.google.mlkit:face-detection:16.0.7'
```

Face detection is working fine.

- Use 16.1.0
```
    implementation 'com.google.mlkit:face-detection:16.1.0'
```

Face detection fails:

```
com.google.mlkit.common.MlKitException: Waiting for the face detection module to be downloaded. Please wait.
```

**Comment by zhouyiself** [comment] 2021-06-01 21:55
Thanks for the report!

This is a known issue (Duplicate of #308 ) and we're working on releasing a new version.

**Closed by zhouyiself** 2021-06-01 21:55 UTC

**Comment by jjkavalam** [comment] 2021-06-02 06:47
Sure. Appreciate the response.
