### ISSUE TITLE
Flickering effect in iOS

### ISSUE THREAD

**Issue by eleiannu** [googlesamples/mlkit#454] opened 2022-03-02 22:53 UTC
I'm experiencing flickering issues when building in Release Mode the Swift Version. I do not get the same unwanted effect when running the ObjectiveC one. In particular, I get it with every detector I try. Do you know what the reason for that could be? (I'm running it on an iPhone 13 Pro)

https://user-images.githubusercontent.com/48253305/156463462-72cb2c35-0997-4059-a7b5-8384f7eafbf1.mp4

**Comment by bcdj** [comment] 2022-03-03 19:32
@eleiannu Have you tried our [quickstart VisionExample sample app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision/VisionExample) which supports [Face Detection](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/CameraViewController.swift#L179).  Do you observe the behavior you saw using the quickstart sample app? If not, you may want to compare your implementation with that app to see whether there are some difference jumping out as the cause.

**Comment by eleiannu** [comment] 2022-03-03 20:43
@bcdj This is the behavior I obtained when using the quickstart sample app, unfortunately!

**Comment by miworking3** [comment] 2022-07-01 16:20
Fixed in the latest version.

**Closed by miworking3** 2022-07-01 16:20 UTC
