### ISSUE TITLE
Face Detection on iOS: empty results for unedited photos from front camera

### ISSUE THREAD

**Issue by ozpopolam** [googlesamples/mlkit#404] opened 2021-12-05 21:29 UTC
Hi!
I've been using **GoogleMLKit/FaceDetection (2.4.0)** for iOS and noticed that in my app faces are never detected for any photos taken with front camera and loaded with UIImagePickerController (either taken in real time or from Photo Library).

The only difference between my code and your demo is that you always scale and reinitiate photos from data before starting detection. It happens in `MLKitExtensions.swift` in `scaledImage(with:)`- method. If I replace the content of this method (so it does nothing) with:
```
public func scaledImage(with size: CGSize) -> UIImage? {
  return self
}
```
I start receiving empty results in demo too. I was able to reproduce it on iPhone 5S (iOS 12.4.8) and XS max (iOS 13.6.1).

Could you explain to me is it necessary to always apply this operation? I'd like to I preform detection on my raw photos (without altering it), but I couldn't find a way to do it.

**Comment by miworking3** [comment] 2021-12-10 21:19
Hi,

We are not able to reproduce it on any of our devices, is this reproducible on all your devices?
# Devices tried:
- iPhone 8 Plus, iOS 12.2
- iPhone 12 Pro, iOS 14.8
- iPhone 8 Plus, iOS 14.8.1
# Steps applied:
- `git clone https://github.com/googlesamples/mlkit.git`
- Change [these lines](https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExample/MLKitExtensions.swift#L14-L17) to `return self`.
- Run face detection from front camera
# Result:
Face is correctly recognized and marked.
Couldn't reproduce the problem mentioned.

**Comment by miworking3** [comment] 2021-12-11 15:28
I'm closing it with not reproducible for now, please feel free to reopen it with reproduce steps and specs, thanks!

**Closed by miworking3** 2021-12-11 15:28 UTC
